// Search user in the database by Email
GET http://localhost:8080/getUserByEmail/viniciussmadeira@gmail.com
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6InZpbmljaXVzc21hZGVpcmFAZ21haWwuY29tIiwiZXhwIjoxNzE4NTc0NDc4LCJpZCI6IjY2NmUwYjhkMWRiYmJlMjNkOWNlNGU5NCIsIm5hbWUiOiJWaW5pY2l1cyBTYW50b3MgTWFkZWlyYSJ9.ORF-VxlONtRx6jj7AhKaTOwSd_TSyWTuiTulVUfwSfs
###

// Search user in the database by ID
GET http://localhost:8080/getUserById/666e0b8d1dbbbe23d9ce4e94
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIzLCJlbWFpbCI6InZpbmljaXVzc21hZGVpcmFAZ21haWwuY29tIiwiZXhwIjoxNzE4NTc0NDc4LCJpZCI6IjY2NmUwYjhkMWRiYmJlMjNkOWNlNGU5NCIsIm5hbWUiOiJWaW5pY2l1cyBTYW50b3MgTWFkZWlyYSJ9.ORF-VxlONtRx6jj7AhKaTOwSd_TSyWTuiTulVUfwSfs
###

// Create a new user
POST http://localhost:8080/createUser
Content-Type: application/json

{
  "email": "viniciussmadeira@gmail.com",
  "password": "clancy123*",
  "name": "Vinicius Santos Madeira",
  "age": 23
}
###

// Updates a user in the database given an ID
PUT localhost:8080/updateUser/666df2e24b1b55d5b2dd693b
Content-Type: application/json

{
  "name": "Vinicius SM",
  "age": 24
}
###

// Deletes a user in the database given an ID
DELETE localhost:8080/deleteUser/666e04ddb7c70682325c4e22
Accept: application/json
###

// Authenticates an user through their email and password
POST localhost:8080/auth
Content-Type: application/json

{
  "email": "viniciussmadeira@gmail.com",
  "password": "clancy123*"
}
###